# something i need

parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\[\033[01;32m\](\t)\[\033[00m\]:\[\033[01;33m\]\u\[\033[01;32m\]@\[\033[01;36m\]\h\[\033[00m\]:\[\033[01;35m\]<\w>\[\033[00m\]\$(parse_git_branch)\[\033[00m\]\n(\#)\$ "
